### ISSUE TITLE
Generated models aren't testable as they are not equatable

### ISSUE THREAD

**Issue by guymclean** [epam-cross-platform-lab/swagger-dart-code-generator#174]
I'm having unit testing issues as when I stub the response from the API that has been generated, I cannot compare expected and actual responses as the generated models don't extend something like Equatable. I think this should probably be done by default, similar to how the copyWith method is generated with the models.

**Comment by Vovanella95** [comment]
Hi @guymclean ,

Need to check options. Possible we can use @freezed package to fix it. Possible we can generate compareTo by our own.

I will try to implement it in 3 days and let you know.


Thanks for this good idea!

**Comment by guymclean** [comment]
Yes freeezed may be a good idea. Thanks a lot! I really enjoy using the package :)

**Comment by Vovanella95** [comment]
@guymclean  freezed brings us a new dependency. I need think about it

**Comment by Vovanella95** [comment]
Hi @guymclean , Enjoy 2.0.4 version in pub.dev!

Note: You need to add collections library. Possible we will rid of it in future. Anyway collections is must have library in each project :D

**Comment by mzdm** [comment]
This is a purely theoretical question ... but I wonder, do you think that is it possible to generate tests as well (if it would be implemented in the generator of course). Because if you're generating a very big amount of APIs (for example Google APIs or etc.) which can have 10, 50, or even 100 APIs, manual testing would be a nightmare.

I would like to contribute such a feature, I don't have much time anytime soon but I wonder if it would be something you would review and you think it is possible and could eventually work.
@Vovanella95 

([google dart apis package](https://github.com/google/googleapis.dart/tree/master/generated/googleapis) is a good example of generated tests, but they use Google Discovery not OpenAPI)

**Comment by Vovanella95** [comment]
hi @mzdm ,

It's good idea to generate tests. We will look into it. Please create new issue to watch it changes.

Thanks for using our generator :)
