### ISSUE TITLE
[BUG] Generation fails for "discriminatorType" element in my swagger file 

### ISSUE THREAD

**Issue by ATeteryatnikov** [epam-cross-platform-lab/swagger-dart-code-generator#311]
if swagger json file has "discriminatorType" element then an error occurs:
"type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast"
 
**To Reproduce**
part of my model for example:

`"V1ListArticle": {
      "allOf": [
        {
          "$ref": "#/definitions/BaseRecord"
        },
        {
          "type": "object",
          "properties": {
            "articleRank": {
              "type": "number"
            },
            "discriminatorType": "#/definitions/V1ListArticle"
          }
        }
      ]
    },`

If I remove "discriminatorType" is work.

**Library version used:**
2.3.5

**Comment by Vovanella95** [comment]
Hi @ATeteryatnikov ,

I have fixed generation error you've described. The only thing - discriminatorType: '#/definitions/V1ListArticle' will not be generated like final V1ListArticle discriminatorType because it's not valid swagger. You can put in into [Swagger editor](https://editor.swagger.io/) and check. 

There are 2 problems:

Semantic error at definitions.V1ListArticle.allOf.0.$ref
$refs must reference a valid location in the document
Jump to line 582

Structural error at definitions.V1ListArticle.allOf.1.properties.discriminatorType
should be object
Jump to line 587

Anyway, your file generating well now. (version 2.3.6 and higher) Enjoy using our generator! :)
