### ISSUE TITLE
[FEATURE] Handling of discriminator

### ISSUE THREAD

**Issue by felixmede** [epam-cross-platform-lab/swagger-dart-code-generator#369]
**Is your feature request related to a problem? Please describe.**
The api config we are using contains, some models with discriminators. This means depending on a specific field inside the class, the class is getting mapped to another class which extends the first class. In other programs languages this feature is called e.g. sealed classes. Flutter currently does not support this but the library freezes is able to create these kind of classes and then map them to the specific subclasses.
Currently the issue is that the class does have any fields of the subclass so all the received information is getting ignored.

**Describe the solution you'd like**
The best solution would be of course to get the classes as sealed classes with e.g. freezed.
The easiest usable solution would be to add all the possible parameters of the possible mapped classes to the normal class and make them nullable. Afterwards the user would be able to access all the information but the checking regarding the needed fields would be up to the user

**Swagger specification link**
[Link to swagger/OpenApi documentation](https://swagger.io/specification/#discriminator-object)

**Comment by Vovanella95** [comment]
Hi @felixmede ,
we already support allOff inheritance.
Unfortunately there are no possibility to support oneOf and anyOf, because type is known only when we received response and there is no way to detect it before. In such cases you can just map response to any generated or custom model you want.

If you have some difficulties, working with out generator, related to discriminators, please let us know.
Also, if you have and idea, how can we generate such things - please provide example of swagger and generated code you'd like to have.

**Comment by Vovanella95** [comment]
Closing this issue. @felixmede please reopen it in case of any ideas
