### ISSUE TITLE
[FEATURE] Improve package code generation

### ISSUE THREAD

**Issue by stevenosse** [epam-cross-platform-lab/swagger-dart-code-generator#437]
**Is your feature request related to a problem? Please describe.*

Hello, we would first like to thank you for the amazing work you've done so far ❤️  !

However, we would like to give you some feedback on the elements we noticed when we tried the package: 

For big projects, you get very large files (I'm at 35000 lines for the template "api.swagger.dart" file). The "separated_models" option only creates a separated file with all the model classes inside.  When those files are pushed to the repository, it makes reviews impossible (because we can't see what changes where made in the file)

**Describe the solution you'd like**

The solution we would suggest :
- Generate one file per template and each file would contain all the info about the template (class definition, extensions, etc...)
- Generate one file per "tag" : For each scheme tag, create a "tag_api" file which will contain all the relative client code, ex: home-controller -> `home_controller_api.dart`
- Generate a file which contains the exports of all the models/all the tags (previously generated)
- Options per request ? (for cache management, header injection on a specific request, etc...)
- **[NIVE TO HAVE]** Use `Object?` instead of `dynamic` when you don't know the type of an object ?
- **[NIVE TO HAVE]** A point that would also be interesting is to use the swagger url as an input. Unless I'm mistaken, today it is absolutely necessary to keep the openapi schema in the project (and thus to version it), whereas one could simply use the url of the swagger doc as an input to get the scheme (as the openapi-generator-cli does)

I don't know if I was clear enough, but these are basically the irritating points we've noticed. If you ever need some clarification on any points or have questions, we'll be happy to answer them.

Have a good day 😃

**Comment by Vovanella95** [comment]
- Hi @stevenosse ! What is problem of huge files? It's anyway generated code and you don't need to investigate it. From my perspective if we will have 1000 files instead of one file with 10000 lines - we will have no advantage. It's not comfortable anyway. But it will be too complicate to support this. So we will generate everything in one file anyway.
- About swagger url as input. No, you don't need to keep this file locally. We just save file locally to have ability to re-generate files, when you have no internet. (For example you have new developer without VPN or smth). Feel free to remove swaggers folder after generation.
- About Object? instead of dynamic. Sounds OK, I will do this in scope of this issue.
- Generation of file, exporting all models is not possible, because we can have models with duplicated names and code will be not valid in this case.
- You can inject any headers into your requests using Interceptors of Chopper client. You can modify any request and any response if needed.

I hope I answered all your questions. Please let me know if everything not clear and in case of new ideas.

**Comment by Vovanella95** [comment]
I'm closing issue. Please reopen it if you not agree with me in any case.
