### ISSUE TITLE
[BUG] Chopper dependency is broken

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#518]
**Describe the bug**
Chopper made a breaking change in 5.2.0 which breaks generated code in this library. More info here: https://github.com/lejard-h/chopper/issues/395

**Comment by RoarGronmo** [comment]
I think Chopper has released 6.0.0 (with at least one breaking change on using `Uri` instead of `String` for url's). AFAIK you should replace `String` with `Uri` on those usages. Secondary, the 5.2.0 version of Chopper also contains the breaking change of replacing `String` with `Uri` (that may have been introduced by accident...).

**Comment by RoarGronmo** [comment]
See that the issue is fixed, when will it published ?

**Comment by Vovanella95** [comment]
Hi @RoarGronmo, next hour :) Just fixing one more issue

**Comment by Vovanella95** [comment]
@RoarGronmo  It's done!
