### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by waldekm** [epam-cross-platform-lab/swagger-dart-code-generator#639]
**I use the separate_models option and always is generated one file.**
What to do to get models in separate files?

**Comment by wolru** [comment]
same issue

**Comment by Vovanella95** [comment]
Hi @waldekm , it's does not make sense to generate models in different files, because you will have a lot of files. Generated code is just generated code, you should not modify it, so when all models are in one file - it's more comfortable to developer. 

Please, provide situation when 100+ files is more comfortable than 1 file with 100+ models.

separate_models means all models will be split from requests in separate file. But each single model will not have separate file.

If you really need this feature, provide situations when it's required. Or feel free to contribute to our package. 

Thanks!

**Comment by waldekm** [comment]
Thank you for response.
I have models with over 80k lines in one file :)
For example, openapi-generator.tech generates all models in separate files.
It's natural that when you write code by hand, there is a dedicated file for each model :)
