### ISSUE TITLE
Models are generated for operations that have not been included (or are explicitly excluded)

### ISSUE THREAD

**Issue by Adam-Langley** [epam-cross-platform-lab/swagger-dart-code-generator#648]
**Describe the bug**
Using the 'include_paths' and/or 'exclude_paths' options, operations can be excluded. Models relating to those excluded operations are not excluded.

**To Reproduce**
In the git example - update build.yaml to look like
```
exclude_paths:
  - "/items/{id}"
  - "/user" # add this line
```

**Expected behavior**
All "user" operations should be removed from .swagger.dart files (this is happening correctly)
HOWEVER
As the "User" model is no longer referenced by any operations, it should also be removed from .swagger.dart files - this is the bug.

**Library version used:**
2.11.10

**Additional context**
This is valuable because for large swagger files, having a massive number of unused model files:
1. wastes CPU time during build_runner, creating the model and serialization dart code.
2. inflates output binaries
3. makes browsing the code (visually) more difficult during debugging

Note: I am aware I can specify the model to exclude in the 'overriden_models' option, however, that requires a massive of manual effort listing all the models, and if you add a model that is still used, then generation files, syntax errors do not clearly reveal the cause, etc etc - it's impractical.

**Comment by Vovanella95** [comment]
Hi @Adam-Langley ,Thanks for raising issue! But I am not gonna implement this issue sorry because of next reasons:
* your case is rare (why such models are added if they are not used?)
* It's not trivial task to define all models should be used
* All not used models will be deleted via tree-shaking

But anyway, feel free to contribute if it's important for you. Let us know in case of any questions!
