### ISSUE TITLE
[FEATURE] Support HTTP 204

### ISSUE THREAD

**Issue by lukasbalaz** [epam-cross-platform-lab/swagger-dart-code-generator#703]
*(NOTE: I am not sure if this is not implemented yet or I just haven't configured the generator correctly)*

**Is your feature request related to a problem? Please describe.**
I am working with an external API that sometimes returns HTTP 204 No Content instead of a response with an empty array. The swagger json looks like this:
```json
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DocumentDtoListResponse"
                }
              }
            }
          },
          "204": {
            "description": "No Content"
          },
          "400": {
            ...
          },
          ...
        }
```
The generated API looks like this:
```dart
Future<chopper.Response<DocumentDtoListResponse>> apiDocumentListPost(...) {...}
```
In case of HTTP 204, it throws a TypeError: `Null check operator used on a null value`.

**Describe the solution you'd like**
In my particular use case, it would be enough if the return type was `Future<chopper.Response<DocumentDtoListResponse?>>` if there was a possibility of a `null` response. I guess this would also be an easy fix for the error.

I understand that in different use cases it may be required to distinguish between different HTTP 2XX codes. I am not sure what would be the best way to do that. But I would be glad if you could implement at least the easy fix for now.

**Swagger specification link**
[Link to swagger/OpenApi documentation](https://swagger.io/docs/specification/describing-responses/#empty)

**Comment by Vovanella95** [comment]
Hi @lukasbalaz, for such situations we can not generate response model, because we do not know which one will be received. You can use response_override_map to set response for request as Map<String, dynamic>, Object etc.

Or (if you have a lot of such requests) we can implement feature to always generate dynamic for  multi-response requests

What do you think?

**Comment by Vovanella95** [comment]
Hi again @lukasbalaz , I've implemented `generate_first_succeed_response` option for such cases.

if `generate_first_succeed_response: true` then generator will generate first succeed response in case of multiple succeed responses.

Otherwise, dynamic response will be generated for request with multiple responses.

For your case, set `generate_first_succeed_response: true` and parse response manually, depending on response code

Let us know in case of any questions or issues
